# Generated by Django 5.0.4 on 2024-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100),
        ),
    ]
